### ISSUE TITLE
Multiple contributions

### ISSUE THREAD

**Issue by sehrgut** [LastLeaf/epub-generator#1]
I've got multiple updates I wrote to support using epub-generator in a side project, which you can see in my fork.
- Fixed generation of invalid chapter IDs
- Sanitized paths to prevent invalid HREFs
- Optionally generate HTML TOC
- Optionally generate HTML title page
- Optional "smarten" title typography
- Support for "subject" tagging (used for categories/collections on many readers)

As a result, examples/basic.js now creates an EPUB which triggers no errors or warnings with either Sigil or FlightCrew.

I know these are a lot of commits, not terribly organized, and you may feel some of them are out-of-scope, so I wasn't sure if you'd like a pull request, or if you'd prefer to merge things manually.

**Comment by LastLeaf** [comment]
Thanks for your contribution. Great job! Feel free to send pull requests.

This project was just a small personal project, originally designed for making mobile-friendly books for myself. I should say sorry if you found my code terrible.
